<?php

// Authoritative disposition map for all public API elements.
// Format: 'Fully\Qualified\ClassName' => 'public|internal|extract|remove'
// This file is verified by PublicSurfaceVerificationTest.

declare(strict_types=1);

return [
    // Layer 0: Foundation — public
    'Waaseyaa\Foundation\Asset\AssetManagerInterface' => 'public',
    'Waaseyaa\Foundation\Broadcasting\BroadcasterInterface' => 'public',
    'Waaseyaa\Foundation\Diagnostic\HealthCheckerInterface' => 'public',
    'Waaseyaa\Foundation\Diagnostic\DiagnosticCode' => 'public',
    'Waaseyaa\Foundation\Log\LoggerInterface' => 'public',
    'Waaseyaa\Foundation\Log\Handler\HandlerInterface' => 'public',
    'Waaseyaa\Foundation\Log\Formatter\FormatterInterface' => 'public',
    'Waaseyaa\Foundation\Log\Processor\ProcessorInterface' => 'public',
    'Waaseyaa\Foundation\Log\LoggerTrait' => 'public',
    'Waaseyaa\Foundation\Log\LogLevel' => 'public',
    'Waaseyaa\Foundation\Middleware\HttpHandlerInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\HttpMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\JobHandlerInterface' => 'public',
    'Waaseyaa\Foundation\Middleware\JobMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\RateLimit\RateLimiterInterface' => 'public',
    'Waaseyaa\Foundation\Schema\SchemaRegistryInterface' => 'public',
    // Schema-evolution v2 (mission #529): diff algebra, compiler output,
    // platform-neutral validation codes, v2 migration authoring contract.
    'Waaseyaa\Foundation\Schema\Diff\OpKind' => 'public',
    'Waaseyaa\Foundation\Schema\Diff\SchemaDiffOp' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\CompiledStep' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\Sqlite\SqliteDiagnosticCode' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\Validation\ValidationDiagnosticCode' => 'public',
    'Waaseyaa\Foundation\Schema\Compiler\Validation\ValidationException' => 'public',
    'Waaseyaa\Foundation\Schema\Migration\MigrationInterfaceV2' => 'public',
    'Waaseyaa\Foundation\Migration\Dag\MigrationKind' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\ServiceProviderInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\ServiceProvider' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\KernelServicesInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\ConfiguresHttpKernelInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasNativeCommandsInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasGraphqlMutationOverridesInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasHttpDomainRoutersInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasMiddlewareInterface' => 'public',
    'Waaseyaa\Foundation\ServiceProvider\Capability\HasRenderCacheListenersInterface' => 'public',
    'Waaseyaa\Foundation\Event\DomainEvent' => 'public',
    'Waaseyaa\Foundation\Event\EventDispatcherInterface' => 'public',
    'Waaseyaa\Foundation\Ingestion\IngestionErrorCode' => 'public',
    'Waaseyaa\Foundation\Exception\WaaseyaaException' => 'public',
    'Waaseyaa\Foundation\Http\HttpServiceResolverInterface' => 'public',
    'Waaseyaa\Foundation\Http\JsonApiResponseTrait' => 'public',
    'Waaseyaa\Foundation\Http\Inbound\InboundHttpRequestInterface' => 'public',
    'Waaseyaa\Foundation\Http\Router\DomainRouterInterface' => 'public',
    'Waaseyaa\Foundation\Http\LanguagePathStripperInterface' => 'public',
    'Waaseyaa\Foundation\Http\Inertia\InertiaFullPageRendererInterface' => 'public',
    'Waaseyaa\Foundation\Http\Inertia\InertiaPageResultInterface' => 'public',
    'Waaseyaa\Foundation\Migration\Migration' => 'public',
    // Schema-evolution v2 ledger verify surface (mission #529 / WP09).
    'Waaseyaa\Foundation\Migration\VerifyResult' => 'public',
    'Waaseyaa\Foundation\Community\CommunityContextInterface' => 'public',
    'Waaseyaa\Foundation\Sovereignty\SovereigntyConfigInterface' => 'public',
    'Waaseyaa\Foundation\Sovereignty\SovereigntyProfile' => 'public',
    'Waaseyaa\Cache\CacheBackendInterface' => 'public',
    'Waaseyaa\Cache\CacheFactoryInterface' => 'public',
    'Waaseyaa\Cache\CacheTagsInvalidatorInterface' => 'public',
    'Waaseyaa\Cache\TagAwareCacheInterface' => 'public',
    'Waaseyaa\Database\DatabaseInterface' => 'public',
    'Waaseyaa\Database\SelectInterface' => 'public',
    'Waaseyaa\Database\InsertInterface' => 'public',
    'Waaseyaa\Database\UpdateInterface' => 'public',
    'Waaseyaa\Database\DeleteInterface' => 'public',
    'Waaseyaa\Database\SchemaInterface' => 'public',
    'Waaseyaa\Database\TransactionInterface' => 'public',
    'Waaseyaa\Plugin\PluginInspectionInterface' => 'public',
    'Waaseyaa\Plugin\PluginManagerInterface' => 'public',
    'Waaseyaa\Plugin\PluginBase' => 'public',
    'Waaseyaa\TypedData\TypedDataInterface' => 'public',
    'Waaseyaa\TypedData\DataDefinitionInterface' => 'public',
    'Waaseyaa\TypedData\ComplexDataInterface' => 'public',
    'Waaseyaa\TypedData\ListInterface' => 'public',
    'Waaseyaa\TypedData\PrimitiveInterface' => 'public',
    'Waaseyaa\TypedData\TypedDataManagerInterface' => 'public',
    'Waaseyaa\TypedData\CastTokenMapper' => 'public',
    'Waaseyaa\TypedData\Coercion\CoercionException' => 'public',
    'Waaseyaa\TypedData\Coercion\EntityCastCoercion' => 'public',
    'Waaseyaa\I18n\LanguageManagerInterface' => 'public',
    'Waaseyaa\I18n\TranslatorInterface' => 'public',
    'Waaseyaa\Queue\QueueInterface' => 'public',
    'Waaseyaa\Testing\Traits\CreatesApplication' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithApi' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithAuth' => 'public',
    'Waaseyaa\Testing\Traits\InteractsWithEvents' => 'public',
    'Waaseyaa\Testing\Traits\RefreshDatabase' => 'public',
    'Waaseyaa\ErrorHandler\SolutionInterface' => 'public',
    'Waaseyaa\ErrorHandler\SolutionProviderInterface' => 'public',

    // Layer 0: Foundation — internal
    'Waaseyaa\Foundation\Kernel\AbstractKernel' => 'internal',
    'Waaseyaa\Foundation\Tenant\TenantResolverInterface' => 'internal',
    'Waaseyaa\Plugin\Discovery\PluginDiscoveryInterface' => 'internal',
    'Waaseyaa\Plugin\Extension\KnowledgeToolingExtensionInterface' => 'internal',
    'Waaseyaa\Plugin\Factory\PluginFactoryInterface' => 'internal',
    'Waaseyaa\Queue\Handler\HandlerInterface' => 'internal',
    'Waaseyaa\Queue\Transport\TransportInterface' => 'internal',
    'Waaseyaa\Queue\FailedJobRepositoryInterface' => 'internal',
    'Waaseyaa\Queue\Job' => 'internal',
    'Waaseyaa\Scheduler\Lock\LockInterface' => 'internal',
    'Waaseyaa\Scheduler\ScheduleInterface' => 'internal',
    'Waaseyaa\State\StateInterface' => 'internal',
    'Waaseyaa\Mail\MailerInterface' => 'internal',
    'Waaseyaa\Mail\Transport\TransportInterface' => 'internal',
    'Waaseyaa\HttpClient\HttpClientInterface' => 'internal',
    'Waaseyaa\Ingestion\PayloadValidatorInterface' => 'internal',
    'Waaseyaa\Ingestion\EnvelopeValidator' => 'internal',
    'Waaseyaa\Testing\WaaseyaaTestCase' => 'internal',

    // Layer 1: Core Data — public
    'Waaseyaa\Entity\EntityInterface' => 'public',
    'Waaseyaa\Entity\EntityBase' => 'public',
    'Waaseyaa\Entity\ContentEntityBase' => 'public',
    'Waaseyaa\Entity\ContentEntityInterface' => 'public',
    'Waaseyaa\Entity\ConfigEntityBase' => 'public',
    'Waaseyaa\Entity\ConfigEntityInterface' => 'public',
    'Waaseyaa\Entity\EntityTypeInterface' => 'public',
    'Waaseyaa\Entity\EntityTypeManagerInterface' => 'public',
    'Waaseyaa\Entity\DefinesEntityType' => 'public',
    'Waaseyaa\Entity\FieldableInterface' => 'public',
    'Waaseyaa\Entity\RevisionableInterface' => 'public',
    'Waaseyaa\Entity\TranslatableInterface' => 'public',
    'Waaseyaa\Entity\TranslatableEntityTrait' => 'public',
    'Waaseyaa\Entity\RevisionableEntityTrait' => 'public',
    'Waaseyaa\Entity\Community\HasCommunityInterface' => 'public',
    'Waaseyaa\Entity\Community\HasCommunityTrait' => 'public',
    'Waaseyaa\Entity\Repository\EntityRepositoryInterface' => 'public',
    'Waaseyaa\Entity\Event\EntityEventFactoryInterface' => 'public',
    'Waaseyaa\Entity\Field\FieldDefinitionRegistryInterface' => 'public',
    'Waaseyaa\Entity\Storage\EntityStorageInterface' => 'public',
    'Waaseyaa\Entity\Storage\RevisionableStorageInterface' => 'public',
    'Waaseyaa\Entity\Storage\EntityQueryInterface' => 'public',
    'Waaseyaa\Entity\Audit\EntityAuditKey' => 'public',
    'Waaseyaa\Entity\Audit\LifecycleAuditKey' => 'public',
    'Waaseyaa\Entity\Event\EntityEvents' => 'public',
    'Waaseyaa\Entity\Hydration\HydratableFromStorageInterface' => 'public',
    'Waaseyaa\Entity\Hydration\HydrationContext' => 'public',
    'Waaseyaa\Entity\Cast\FromArrayEntityValueInterface' => 'public',
    'Waaseyaa\Entity\EntityValues' => 'public',
    'Waaseyaa\Entity\Snapshot\EntityValuesSnapshot' => 'public',
    'Waaseyaa\Entity\DateTime\EntityClockInterface' => 'public',
    'Waaseyaa\Entity\DateTime\UtcEntityClock' => 'public',
    'Waaseyaa\Entity\DateTime\FixedEntityClock' => 'public',
    'Waaseyaa\Entity\DateTime\TimestampFieldConvention' => 'public',
    'Waaseyaa\EntityStorage\Driver\EntityStorageDriverInterface' => 'public',
    'Waaseyaa\EntityStorage\Connection\ConnectionResolverInterface' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnknownFieldException' => 'public',
    'Waaseyaa\EntityStorage\Exception\BundleAmbiguousFieldException' => 'public',
    // entity-storage-v2 mission public surface (WP01–WP12, M-001)
    'Waaseyaa\EntityStorage\RevisionableEntityStorageInterface' => 'public',
    // WP01 — backend registration
    'Waaseyaa\EntityStorage\Backend\FieldStorageBackendInterface' => 'public',
    'Waaseyaa\EntityStorage\Backend\HasFieldStorageBackendsInterface' => 'public',
    'Waaseyaa\EntityStorage\Backend\IsFrameworkBackendProviderInterface' => 'public',
    'Waaseyaa\EntityStorage\Backend\ReservedBackendIds' => 'public',
    'Waaseyaa\EntityStorage\Backend\BackendRegistrar' => 'public',
    'Waaseyaa\EntityStorage\Backend\BackendRegistrarFactory' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnsupportedQueryException' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnsupportedListingException' => 'public',
    // WP02 — coordinator
    'Waaseyaa\EntityStorage\EntityStorageCoordinator' => 'public',
    'Waaseyaa\EntityStorage\BackendResolver' => 'public',
    'Waaseyaa\EntityStorage\Exception\UnknownBackendException' => 'public',
    // WP03 — sql-blob backend
    'Waaseyaa\EntityStorage\Backend\SqlBlobBackend' => 'public',
    // WP04 — lifecycle events
    'Waaseyaa\EntityStorage\Event\EntityLifecycleEventInterface' => 'public',
    'Waaseyaa\EntityStorage\Event\BeforeSaveEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\AfterSaveEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\BeforeDeleteEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\AfterDeleteEvent' => 'public',
    'Waaseyaa\EntityStorage\Event\AbortOperationException' => 'public',
    'Waaseyaa\EntityStorage\Exception\PartialSaveException' => 'public',
    'Waaseyaa\EntityStorage\SaveContext' => 'public',
    'Waaseyaa\EntityStorage\CoordinatorLifecycleDispatcher' => 'public',
    // WP05 — sql-column backend
    'Waaseyaa\EntityStorage\Backend\SqlColumnBackend' => 'public',
    'Waaseyaa\EntityStorage\Backend\SqlColumnSchemaBuilder' => 'public',
    'Waaseyaa\EntityStorage\Backend\SqlColumnQueryTranslator' => 'public',
    'Waaseyaa\EntityStorage\Backend\TypeMapping' => 'public',
    // WP06 — definition validator
    'Waaseyaa\EntityStorage\Query\DefinitionValidator' => 'public',
    // WP07 — revisionable entities (entity package)
    'Waaseyaa\Entity\RevisionableEntityInterface' => 'public',
    'Waaseyaa\Entity\RevisionableEntityTrait' => 'public',
    'Waaseyaa\Entity\RevisionMetadata' => 'public',
    'Waaseyaa\EntityStorage\Schema\RevisionTableBuilder' => 'public',
    // WP08 — revisionable storage
    'Waaseyaa\EntityStorage\RevisionableSqlBlobStorage' => 'public',
    'Waaseyaa\EntityStorage\RevisionableSqlColumnStorage' => 'public',
    'Waaseyaa\EntityStorage\RevisionPruner' => 'public',
    'Waaseyaa\EntityStorage\RevisionPruningPolicy' => 'public',
    'Waaseyaa\EntityStorage\RevisionPruningReport' => 'public',
    // WP09 — revision access (access package)
    'Waaseyaa\Access\Gate\RevisionAccessRouter' => 'public',
    // WP10 — migration CLI (cli package)
    'Waaseyaa\CLI\Handler\MakeStorageMigrationHandler' => 'public',
    'Waaseyaa\CLI\Provider\MakeStorageMigrationServiceProvider' => 'public',
    'Waaseyaa\CLI\Command\Migration\StorageMigrationEmitter' => 'public',
    'Waaseyaa\CLI\Command\Migration\StorageMigrationTemplate' => 'public',
    'Waaseyaa\CLI\Command\Migration\BackfillHelper' => 'public',
    'Waaseyaa\CLI\Command\Migration\UnmappedFieldTypeException' => 'public',
    'Waaseyaa\CLI\Command\Migration\BackfillRowCountMismatchException' => 'public',
    // WP12 — conformance test harness (autoload-dev only; still part of stable surface for extenders)
    'Waaseyaa\EntityStorage\Testing\Contract\FieldStorageBackendContractTestCase' => 'public',
    // EntityQuery marker interface
    'Waaseyaa\EntityStorage\Query\EntityQuery' => 'public',
    // entity-storage-translations-v1 mission public surface (M-006, ADR 017)
    // `TranslatableInterface` (already listed above) is the stable contract; `language()` retained as deprecated alias for `activeLangcode()`.
    'Waaseyaa\Entity\Exception\EntityTranslationException' => 'public',
    'Waaseyaa\Entity\Event\EntityEvent' => 'public',
    'Waaseyaa\Entity\Event\TranslationEvent' => 'public',
    'Waaseyaa\Entity\Hydration\FallbackChainResolver' => 'public',
    // Conformance test harness for `TranslatableInterface` implementations.
    'Waaseyaa\Entity\Testing\Translation\TranslatableEntityContractTest' => 'public',
    'Waaseyaa\Access\AccountInterface' => 'public',
    'Waaseyaa\Access\AccessPolicyInterface' => 'public',
    'Waaseyaa\Access\ContextAwareAccessPolicyInterface' => 'public',
    'Waaseyaa\Access\FieldAccessPolicyInterface' => 'public',
    'Waaseyaa\Access\PermissionHandlerInterface' => 'public',
    'Waaseyaa\Access\Gate\GateInterface' => 'public',
    'Waaseyaa\Access\AccessStatus' => 'public',
    'Waaseyaa\Auth\Config\MailMissingPolicy' => 'public',
    'Waaseyaa\Config\ConfigInterface' => 'public',
    'Waaseyaa\Config\ConfigFactoryInterface' => 'public',
    'Waaseyaa\Config\ConfigManagerInterface' => 'public',
    'Waaseyaa\Config\StorageInterface' => 'public',
    'Waaseyaa\Config\TranslatableConfigFactoryInterface' => 'public',
    'Waaseyaa\Config\Event\ConfigEvents' => 'public',
    'Waaseyaa\Field\FieldItemInterface' => 'public',
    'Waaseyaa\Field\FieldItemListInterface' => 'public',
    'Waaseyaa\Field\FieldDefinitionInterface' => 'public',
    'Waaseyaa\Field\FieldStorage' => 'public',
    'Waaseyaa\Field\FieldTypeInterface' => 'public',
    'Waaseyaa\Field\FieldFormatterInterface' => 'public',
    'Waaseyaa\Field\FieldTypeManagerInterface' => 'public',
    'Waaseyaa\Field\FieldItemBase' => 'public',
    'Waaseyaa\Field\Item\LabeledCase' => 'public',
    'Waaseyaa\Field\ViewModeConfigInterface' => 'public',

    // Layer 1: Core Data — internal
    'Waaseyaa\EntityStorage\Hydration\EntityInstantiator' => 'internal',
    'Waaseyaa\Access\ErrorPageRendererInterface' => 'internal',
    'Waaseyaa\Field\ComputedFieldInterface' => 'internal',
    'Waaseyaa\Auth\Token\AuthTokenRepositoryInterface' => 'internal',
    'Waaseyaa\Auth\RateLimiterInterface' => 'internal',

    // Layer 2: Content Types — public
    'Waaseyaa\Media\FileRepositoryInterface' => 'public',
    'Waaseyaa\Path\PathAliasManagerInterface' => 'public',
    'Waaseyaa\Relationship\VisibilityFilterInterface' => 'public',
    'Waaseyaa\NorthCloud\Sync\NcHitToEntityMapperInterface' => 'public',
    'Waaseyaa\NorthCloud\Sync\NcHitSupportDiagnosticsInterface' => 'public',

    // Layer 3: Services — public
    'Waaseyaa\Search\SearchProviderInterface' => 'public',
    'Waaseyaa\Search\SearchIndexerInterface' => 'public',
    'Waaseyaa\Search\SearchIndexableInterface' => 'public',
    'Waaseyaa\Notification\NotificationInterface' => 'public',
    'Waaseyaa\Notification\NotifiableInterface' => 'public',
    'Waaseyaa\Notification\NotifiableTrait' => 'public',
    'Waaseyaa\Notification\ChannelInterface' => 'public',
    'Waaseyaa\Billing\PlanTier' => 'public',
    // Migration platform plugin contracts (mission migration-platform-v1-01KRCDE9 WP01).
    'Waaseyaa\Migration\Plugin\SourcePluginInterface' => 'public',
    'Waaseyaa\Migration\Plugin\ProcessPluginInterface' => 'public',
    'Waaseyaa\Migration\Plugin\DestinationPluginInterface' => 'public',
    'Waaseyaa\Migration\Discovery\HasMigrationPluginsInterface' => 'public',

    // Layer 3: Services — internal
    'Waaseyaa\Billing\StripeClientInterface' => 'internal',

    // Layer 4: API — public
    'Waaseyaa\Api\CodifiedContext\CodifiedContextSessionStoreInterface' => 'public',
    'Waaseyaa\Api\MutableTranslatableInterface' => 'public',
    'Waaseyaa\Routing\Language\LanguageNegotiatorInterface' => 'public',

    // Layer 5: AI — public
    'Waaseyaa\AI\Agent\AgentInterface' => 'public',
    'Waaseyaa\AI\Agent\ToolRegistryInterface' => 'public',
    'Waaseyaa\AI\Agent\Provider\ProviderInterface' => 'public',
    'Waaseyaa\AI\Agent\Provider\StreamingProviderInterface' => 'public',
    'Waaseyaa\AI\Pipeline\PipelineStepInterface' => 'public',
    'Waaseyaa\AI\Vector\VectorStoreInterface' => 'public',
    'Waaseyaa\AI\Vector\EmbeddingProviderInterface' => 'public',
    'Waaseyaa\AI\Vector\EmbeddingInterface' => 'public',
    'Waaseyaa\AI\Vector\EmbeddingStorageInterface' => 'public',
    'Waaseyaa\AI\Vector\DistanceMetric' => 'public',
    'Waaseyaa\AI\Observability\Recorder\TraceRecorderInterface' => 'public',
    'Waaseyaa\AI\Observability\Value\BudgetDecision' => 'public',
    'Waaseyaa\Bimaaji\Graph\GraphSectionProviderInterface' => 'public',

    // Layer 6: Interfaces — public
    'Waaseyaa\CLI\Ingestion\SourceConnectorInterface' => 'public',
    // WP04: native CLI kernel
    'Waaseyaa\CLI\CliKernel' => 'public',
    'Waaseyaa\CLI\Provider\CliKernelServiceProvider' => 'public',
    'Waaseyaa\AdminSurface\Action\SurfaceActionHandlerInterface' => 'public',
    'Waaseyaa\AdminSurface\Query\SurfaceFilterOperator' => 'public',
    'Waaseyaa\AdminSurface\Host\AbstractAdminSurfaceHost' => 'public',
    'Waaseyaa\Bimaaji\Graph\GraphSectionProviderInterface' => 'public',
    'Waaseyaa\Mcp\Bridge\ToolExecutorInterface' => 'public',
    'Waaseyaa\Mcp\Bridge\ToolRegistryInterface' => 'public',
    'Waaseyaa\Mcp\Auth\McpAuthInterface' => 'public',
    'Waaseyaa\Oidc\Keys\OidcKeyLoaderInterface' => 'public',
    'Waaseyaa\Oidc\Repository\AuthorizationCodeRepositoryInterface' => 'public',
    'Waaseyaa\SSR\ThemeInterface' => 'public',

    // Layer 1: Core Data — public (discovered during L5-L6 scan)
    'Waaseyaa\OAuthProvider\OAuthProviderInterface' => 'public',
    'Waaseyaa\OAuthProvider\SessionInterface' => 'public',

    // Layer 3: Services — public (single-entity-work-surface-01KQ7M1P)
    'Waaseyaa\StructuredImport\StructuredImporterInterface' => 'public',

    // Layer 6: CLI native kernel — WP02 (native-cli-kernel-01KR2NR7)
    'Waaseyaa\CLI\ArgumentMode' => 'public',
    'Waaseyaa\CLI\CliIO' => 'public',
    'Waaseyaa\CLI\OptionMode' => 'public',
    'Waaseyaa\CLI\Parser\ParseErrorKind' => 'public',

    // Layer 6: CLI native kernel — WP03 (native-cli-kernel-01KR2NR7)
    'Waaseyaa\CLI\Io\CliInput' => 'public',
    'Waaseyaa\CLI\Io\CliOutput' => 'public',
    'Waaseyaa\CLI\Io\StdinSource' => 'public',

    // Layer 6: Interfaces — internal
    'Waaseyaa\Telescope\Storage\TelescopeStoreInterface' => 'internal',
    'Waaseyaa\Telescope\CodifiedContext\Validator\EmbeddingProviderInterface' => 'internal',
    'Waaseyaa\Telescope\CodifiedContext\Storage\CodifiedContextStoreInterface' => 'internal',
    'Waaseyaa\CLI\Command\Make\AbstractMakeCommand' => 'internal',
    'Waaseyaa\CLI\Command\Make\AbstractMakeHandler' => 'internal',
    'Waaseyaa\Mcp\Tools\McpTool' => 'internal',
    'Waaseyaa\SSR\Http\AppController\AppControllerArgumentResolver' => 'public',
    'Waaseyaa\SSR\Http\AppController\AppParameterKind' => 'public',
];
